# config.yaml

device: "cuda:0"

pix_to_pix:
  model_id: "timbrooks/instruct-pix2pix"
  steps: 50
  randomize_seed: False
  seed: 42
  randomize_cfg: False
  text_cfg_scale: 7.5
  image_cfg_scale: 1.5
  torch_dtype: "torch.float16"
  safety_checker: None

Zodiac:
  method: 'ZoDiac'
  save_img: './example/output/'
  model_id: 'stabilityai/stable-diffusion-2-1-base'
  gen_seed: 0
  empty_prompt: True
  w_type: 'single'
  w_channel: 3
  w_radius: 10
  w_seed: 10
  start_latents: 'init_w'
  iters: 100
  save_iters: [100]
  loss_weights: [10.0, 0.1, 1.0, 0.0]
  ssim_threshold: 0.92
  detect_threshold: 0.9
