Editor:
  pix2pix:
    device: "cuda"
    model_id: "timbrooks/instruct-pix2pix"
    steps: 50
    randomize_seed: False
    seed: 42
    randomize_cfg: False
    text_cfg_scale: 7.5
    image_cfg_scale: 1.5
    safety_checker: None

Watermarker:
  WAM:
    device: "cuda"
    seed: 42
    epsilon: 1.0
    min_samples: 500
    proportion_masked: 0.5
    exp_dir: "checkpoints"
    save_dir: "Watermarked/WAM"

WandB:
  project_name: "Text Based Image Editing"
  run_name: "0_random_140"