# config.yaml

device: "cuda:0"

dirs:
  original_image: "data/input/"
  watermarked_image: "data/watermarked/"
  generated_image_1: "data/generated_1/"
  generated_image_2: "data/generated_2/"
  generated_image_3: "data/generated_3/"
  generated_image_4: "data/generated_4/"
  generated_image_5: "data/generated_5/"

pix_to_pix:
  model_id: "timbrooks/instruct-pix2pix"
  steps: 50
  randomize_seed: False
  seed: 42
  randomize_cfg: False
  text_cfg_scale: 7.5
  image_cfg_scale: 1.5
  torch_dtype: "torch.float16"
  safety_checker: None

turbo_edit:
  sdxl_model: "stabilityai/sdxl-turbo"
  num_steps_inversion: 5
  strength: 0.5
  generator: None
  seed: 7 
  ws1: [1.5, 1.5, 1.5, 1.5]
  ws2: [1, 1, 1, 1]
  denoising_start: 0.2
  images_paths: null
  images_folder: null
  force_use_cpu: false
  folder_name: "test_measure_time"
  config_from_file: "run_configs/noise_shift_guidance_1_5.yaml"
  save_intermediate_results: false
  batch_size: null
  skip_p_to_p: true
  only_p_to_p: false
  fp16: false
  prompts_file: "dataset_measure_time/dataset.json"
  images_in_prompts_file: null
  seed: 986
  time_measure_n: 1

Zodiac:
  method: 'ZoDiac'
  save_img: './data/watermarked/'
  model_id: 'stabilityai/stable-diffusion-2-1-base'
  gen_seed: 0
  empty_prompt: True
  w_type: 'single'
  w_channel: 3
  w_radius: 10
  w_seed: 10
  start_latents: 'init_w'
  iters: 100
  save_iters: [100]
  loss_weights: [10.0, 0.1, 1.0, 0.0]
  ssim_threshold: 0.92
  detect_threshold: 0.9
